dlcdb/licenses/urls.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.urls import path
from . import views

app_name = "licenses"

urlpatterns = [
    path("<int:license_id>/history/", views.history, name="history"),
    path("<int:license_id>/edit/", views.edit, name="edit"),
    path("new/", views.new, name="new"),
    path("playground/", views._playground, name="playground"),
    path("", views.index, name="index"),
]

dlcdb/urls.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy
from django.contrib import admin
from django.views.generic.base import RedirectView

from dlcdb.organization import views as organization_views

admin.site.site_header = "DLCDB Admin"
admin.site.site_title = "DLCDB Admin"
admin.site.index_title = "DLCDB Administration"
admin.site.enable_nav_sidebar = False
admin.site.logout_template = "accounts/logout.html"


urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("core:core_dashboard"))),
    path("core/", include("dlcdb.core.urls")),
    path("inventory/", include("dlcdb.inventory.urls")),
    path("licenses/", include("dlcdb.licenses.urls")),
    path("smallstuff/", include("dlcdb.smallstuff.urls")),
    path("select2/", include("django_select2.urls")),
    path("api/v2/", include("dlcdb.api.urls")),
    path("favicon.ico", organization_views.favicon),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

dlcdb/licenses/models.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.db import models
from django.utils.translation import gettext_lazy as _

from ..core.models.abstracts import SingletonBaseModel


class LicensesConfiguration(SingletonBaseModel):
    default_subscribers = models.ManyToManyField(
        "core.Person",
        related_name="+",
        blank=True,
        help_text=_("These subscribers will be added to all new licenses by default."),
    )

    def __str__(self):
        return "Licenses configuration"

    class Meta:
        verbose_name = _("Licenses configuration")
        verbose_name_plural = _("Licenses configuration")

dlcdb/licenses/forms.py
from django import forms
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
# from django.core.validators import validate_email

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div, HTML
from crispy_bootstrap5.bootstrap5 import FloatingField

from dlcdb.core.models import Device, DeviceType, Person
from .subscribers import manage_subscribers


class LicenseForm(forms.ModelForm):
    contract_termination = forms.BooleanField(
        required=False,
        # The initial value will be set in the __init__ method
        help_text=_("Check this box if the contract has been terminated."),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Check if this is an edit form (instance exists)
        self.is_edit = self.instance and self.instance.pk is not None

        # Limit device-type choices to "License-type" choices
        self.fields["device_type"].queryset = DeviceType.objects.filter(
            Q(name__startswith="Lizenz::") | Q(name__startswith="License::") | Q(name__startswith="Licence::")
        )
        # Set initial value for contract_termination checkbox
        self.fields["contract_termination"].initial = bool(self.instance.contract_termination_date)

        # Dynamically set initial subscribers
        # if self.is_edit:
        #     current_subscribers = self.instance.subscription_set.values_list("subscriber_id", flat=True)
        #     self.fields["subscribers"].initial = current_subscribers

        # Reset queryset each time to avoid caching
        self.fields["subscribers"] = forms.ModelMultipleChoiceField(
            queryset=Person.objects.filter(email__isnull=False),
            required=False,
            help_text=_("Select one or more subscribers."),
            widget=forms.SelectMultiple(
                attrs={
                    "class": "is-tom-select",
                    # "data-placeholder": "-----",
                }
            ),
            initial=self.instance.subscription_set.values_list("subscriber_id", flat=True)
            if self.instance.pk
            else None,
        )

        # Crispy forms
        self.helper = FormHelper()
        self.helper.form_tag = False

        self.helper.layout = Layout(
            Row(
                Column("sap_id", css_class="col-md-4"),
                Column("subscribers", css_class="col-md-8"),
            ),
            Div(HTML("<hr>")),
            Row(
                Column(FloatingField("manufacturer"), css_class="col-md-4"),
                Column(FloatingField("series"), css_class="col-md-6"),
            ),
            Row(
                Column(FloatingField("supplier"), css_class="col-md-4"),
                Column(FloatingField("order_number"), css_class="col-md-3"),
                Column(FloatingField("device_type"), css_class="col-md-3"),
            ),
            Div(
                Row(
                    Column(FloatingField("contract_start_date"), css_class="col-md-3"),
                    Column(FloatingField("contract_expiration_date"), css_class="col-md-3"),
                    # The field "contract_termination" is only shown in edit mode:
                    Column("contract_termination", css_class="col-md-3 offset-md-3") if self.is_edit else None,
                ),
                css_class="alert alert-info",
            ),
            Row(
                Column(FloatingField("note"), css_class="col-md-6"),
                Column(FloatingField("procurement_note"), css_class="col-md-6"),
            ),
        )

    def clean(self):
        cleaned_data = super().clean()
        if not any(cleaned_data.values()):
            raise ValidationError(_("At least one field must be filled."))

    def save(self, commit=True):
        instance = super().save(commit=False)

        # The database field is a DateTimeField, so we cast the BoolenField to
        # a DateTimeField.
        if self.cleaned_data.get("contract_termination"):
            instance.contract_termination_date = timezone.now()
        else:
            instance.contract_termination_date = None

        instance.save()
        self.save_m2m()

        subscribers = self.cleaned_data.get("subscribers")
        manage_subscribers(instance, subscribers)

        return instance

    class Meta:
        model = Device
        fields = [
            "sap_id",
            "supplier",
            "order_number",
            "book_value",
            "manufacturer",
            "series",
            "contract_start_date",
            "contract_expiration_date",
            "procurement_note",
            "note",
            "device_type",
            "contract_termination",
        ]
        labels = {
            "subscribers": _("Subscribers"),
            "device_type": _("Type"),
            "series": _("Name"),
            "contract_start_date": _("Start Date"),
            "contract_expiration_date": _("Expiration Date"),
        }
        widgets = {
            # Must set the date format, otherwise the date input field
            # is not populated from the model instance.
            "contract_expiration_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
            "contract_start_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
            "note": forms.Textarea(attrs={"rows": 6, "style": "resize: vertical; height: 10em;"}),
            "procurement_note": forms.Textarea(attrs={"rows": 6, "style": "resize: vertical; height: 10em;"}),
        }

dlcdb/licenses/views.py
from itertools import chain
from operator import attrgetter

from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db import transaction, IntegrityError
from django.http import HttpResponse
from django.urls import reverse
from django.utils.translation import gettext as _

from django_htmx.http import HttpResponseClientRedirect

from dlcdb.core.models import LicenceRecord, Device, InRoomRecord, Room
from .forms import LicenseForm
from .decorators import htmx_permission_required
from .filters import LicenceRecordFilter
from .models import LicensesConfiguration


@login_required
def _playground(request):
    """
    Just a temporary playground view.
    """
    template = "licenses/playground.html"
    context = {}

    return TemplateResponse(request, template, context)


@login_required
def index(request):
    if request.htmx:
        template = "licenses/licenses_table.html"
    else:
        template = "licenses/index.html"

    base_qs = LicenceRecord.objects.all().order_by("-device__modified_at")
    license_record_filter = LicenceRecordFilter(request.GET, queryset=base_qs)

    context = {
        "licenses_filtered": license_record_filter.qs.count(),
        "licenses_total": base_qs.count(),
        "license_record_filter": license_record_filter,
    }

    return TemplateResponse(request, template, context)


@login_required
@htmx_permission_required("core.change_licencerecord")
def edit(request, license_id):
    if request.htmx:
        template = "licenses/form_partial.html"
    else:
        # raise NotImplementedError("Non HTMX requests not implemented")
        template = "licenses/form.html"

    license = get_object_or_404(Device, id=license_id)

    if request.method == "POST":
        form = LicenseForm(
            request.POST,
            instance=license,
        )

        if form.is_valid():
            device = form.save(commit=False)
            device.save()

            messages.success(
                request,
                f"License {device.sap_id} saved.",
            )

            # The plain return redirect() behaves differently than the HX-Redirect header
            # return redirect("licenses:index")
            # This redirect is also available in the Django HTMX package:
            # return HttpResponseClientRedirect(redirect_url)
            if request.htmx:
                response = HttpResponse(status=204)
                response["HX-Redirect"] = reverse("licenses:index")
                return response
            else:
                return redirect("licenses:index")

    else:
        # GET request
        form = LicenseForm(
            instance=license,
        )

    return TemplateResponse(
        request,
        template,
        {
            "form": form,
            "license": license,
            "template": template,
            "title": _("Edit license"),
            "obj_admin_url": reverse("admin:core_device_change", args=[license.id]),
        },
    )


@login_required
@htmx_permission_required("core.change_licencerecord")
def new(request):
    if request.htmx:
        template = "licenses/form_partial.html"
    else:
        raise NotImplementedError("Non HTMX requests not implemented")

    if request.method == "POST":
        form = LicenseForm(
            request.POST,
        )

        if form.is_valid():
            errors = []

            try:
                with transaction.atomic():
                    # The form.is_valid() call will trigger the custom validation
                    # defined in your LicenseForm class's clean() method
                    device = form.save(commit=False)

                    # Set device properties
                    device.is_licence = True
                    device.save()

                    # Set record and room for device
                    room = Room.objects.get(is_default_license_room=True)

                    record = InRoomRecord(
                        device=device,
                        room=room,
                        user=request.user,
                        username=request.user.username,
                    )
                    record.save()

            except Room.DoesNotExist:
                errors.append("No license room/location defined. Define a license room first.")
            except ValidationError as e:
                errors.append(str(e))
            except IntegrityError as e:
                errors.append(f"Database error: Could not save the license. Please try again. Error: {e}")
            except Exception as e:
                errors.append(f"An error occurred while saving: {e}")

            if errors:
                for error in errors:
                    messages.error(request, error)
            else:
                messages.success(
                    request,
                    f"License {device.sap_id} added.",
                )

            redirect_url = reverse("licenses:index")
            return HttpResponseClientRedirect(redirect_url)
    else:
        # Set default subscribers
        default_subscribers = LicensesConfiguration.load().default_subscribers.all()
        form = LicenseForm(initial={"subscribers": default_subscribers})

    return TemplateResponse(
        request,
        template,
        {
            "form": form,
            "template": template,
            "title": _("New license"),
        },
    )


@login_required
@htmx_permission_required("core.change_licencerecord")
def history(request, license_id):
    device = get_object_or_404(Device, id=license_id)
    device_history = device.history.all()

    # subscription_model = device.subscription_set.model
    # deleted_subscription_history = subscription_model.history.filter(device_id=device.id)
    # Currently we do not need the combined history of multiple models
    # as the subscribers changes are tracked manually with the
    # update_change_reason function.
    combined_history = sorted(chain(device_history), key=attrgetter("history_date"), reverse=True)

    # Use a generator function to yield history entries with diffs
    def get_history_with_diffs():
        history_list = list(combined_history)
        for i in range(len(history_list) - 1):
            record = history_list[i]
            next_record = history_list[i + 1]

            # Check if both records are from the same model
            if isinstance(record.instance, type(next_record.instance)):
                # They are the same model; compute the diff
                delta = record.diff_against(
                    next_record, foreign_keys_are_objs=True, excluded_fields=["id", "active_record", "subscriber"]
                )
                # Skip if no changes detected
                if not delta.changes and not record.history_change_reason:
                    continue
            else:
                # Different models; cannot compute diff
                # delta = None
                if not record.history_change_reason:
                    continue

            yield (record, delta)

        # Handle the last record
        if history_list and history_list[-1].history_change_reason:
            yield (history_list[-1], None)
        # Handle the last record
        if history_list:
            yield (history_list[-1], None)

    return TemplateResponse(
        request,
        "licenses/history.html",
        {
            "history": get_history_with_diffs(),
            "license": device,
            "title": _("License History"),
        },
    )

dlcdb/licenses/templates/licenses/filters.html
{% load i18n %}

<div class="search flex-grow-1 me-4">
  <form
    hx-get="{% url 'licenses:index' %}"
    hx-target="#licenses-list"
    hx-push-url="true"
    hx-trigger="keyup changed delay:250ms, search, change"
    >
    <div class="input-group mb-3">

      <span class="input-group-text">
        <i class="bi bi-search"></i>
      </span>

      <input
          type="search"
          class="form-control"
          style="flex-grow: 3;"
          placeholder="{% translate 'Search licenses' %}"
          name="{{ license_record_filter.form.search.html_name }}"
          id="{{ license_record_filter.form.search.id_for_label }}"
          value="{{ license_record_filter.form.search.value|default:"" }}"
      >

      <select class="form-select" name="device__device_type">
        {% for choice in license_record_filter.form.device__device_type %}
          {{ choice }}
        {% endfor %}
      </select>

      <select class="form-select" name="device__supplier">
        {% for choice in license_record_filter.form.device__supplier %}
          {{ choice }}
        {% endfor %}
      </select>

      <select class="form-select" name="license_state">
        {% for choice in license_record_filter.form.license_state %}
          {{ choice }}
        {% endfor %}
      </select>
    </div>
  </form>
</div>

dlcdb/licenses/templates/licenses/form.html
{% extends "theme/_base.html" %}
{% load static i18n crispy_forms_tags %}

{% block body %}
    <h1>{% translate "Licenses" %}</h1>
    {% include "licenses/form_partial.html" %}
{% endblock body %}

dlcdb/licenses/templates/licenses/form_partial.html
{% load i18n crispy_forms_tags %}


<div class="d-flex align-items-center mb-4">
    <div>
        <h2 class="mb-0 me-4">
            {{ title }}
        </h2>
    </div>
    <div>
        {% if license %}
            {% if request.user.is_staff %}
            <a
                href="{{ obj_admin_url }}"
                class="btn text-bg-warning btn-sm"
            >
                <i class="bi bi-box-arrow-up-right"></i>
                {% translate 'Admin view' %}
            </a>
            {% endif %}


        <a
            href="{% url 'licenses:history' license.id %}"
            class="btn text-bg-warning btn-sm"
        >
            <i class="bi bi-clock-history"></i>
            {% translate 'Show history' %}
        </a>
        {% endif %}
    </div>
</div>

{% if license %}
    {% include 'licenses/timeline.html' with events=license.get_timeline %}
{% endif %}

<form
    id="license-form"
    method="POST"
    action="
        {% if license %}
            {% url 'licenses:edit' license_id=license.id %}
        {% else %}
            {% url 'licenses:new' %}
        {% endif %}
    "
    {% if request.htmx %}
    hx-post="
        {% if license %}
            {% url 'licenses:edit' license_id=license.id %}
        {% else %}
            {% url 'licenses:new' %}
        {% endif %}
    "
    hx-target="#licenses-content-wrapper"
    {% endif %}
>
    {% crispy form %}

    <button
        type="submit"
        class="my-4 btn btn-primary"
    >
        {% translate "Save" %}
    </button>
    <span
        class="my-4 btn btn-secondary ms-2"
        hx-get="{% url 'licenses:index' %}"
        hx-target="#licenses-content-wrapper"
    >
        {% translate "Cancel" %}
    </span>
</form>

dlcdb/licenses/templates/licenses/history.html
{% extends "theme/_base.html" %}

{% block title %}
    History for {{ license }}
{% endblock %}


{% block body %}

<div class="d-flex align-items-center mb-4">
  <div>
      <h2 class="mb-0 me-4">
        History for {{ license }}
      </h2>
  </div>
  <div>
    <a
        href="{% url 'licenses:edit' license.id %}"
        class="btn text-bg-warning btn-sm"
    >
        <i class="bi bi-pencil-square"></i>
        Edit
    </a>
  </div>
</div>



<ul>
    {% for entry, delta in history %}
        <li class="rounded border p-3 mb-3">
            <div class="row">
                <div class="col-4">

                    <strong>
                        <span class="me-2">
                          {{ entry.history_date }}
                        </span>
                        <br>
                        <span class="badge text-bg-secondary">
                          <i class="bi bi-person-fill"></i> 
                          {{ entry.history_user }} 
                        </span>
                        <i class="fw-normal ms-4">
                          {% if entry.history_type == '+' %}
                          <i class="bi bi-plus-circle-fill text-success"></i>
                          {% elif entry.history_type == '~' %}
                          <i class="bi bi-pencil-fill text-warning"></i>
                          {% elif entry.history_type == '-' %}
                          <i class="bi bi-dash-circle-fill text-danger"></i>
                          {% else %}
                          <i class="bi bi-circle-fill text-secondary"></i>
                          {% endif %}
                          {{ entry.get_history_type_display }}
                        </i>

                    </strong>
                    <p class="small">
                        <!-- {{ entry.history_id }}:  -->
                        <!-- {{ entry.history_object }} -->
                    </p>
                </div>
                <div class="col-8">

                  {% if entry.history_change_reason %}
                    <p>
                      {{ entry.history_change_reason }}
                    </p>
                  {% endif %} 
                    {% if delta.changes %}
                    <small>
                        <table class="table table-sm">
                          <thead class="table-light">
                            <tr>
                              <th>Field</th>
                              <th>From</th>
                              <th>To</th>
                            </tr>
                          </thead>
                          <tbody>
          
                        {% for change in delta.changes %}
                        <tr>
                          <td>{{ change.field }}</td>
                          <td>{{ change.old }}</td>
                          <td>{{ change.new }}</td>
                        </tr>
                        {% empty %}
                            <p>No history for this item has been logged yet.</p>
                        {% endfor %}
                        </tbody>
                        </table>
                      </small>
                    {% endif %}

                </div>
            </div>
        </li>
    {% endfor %}
</ul>
{% endblock %}

dlcdb/licenses/templates/licenses/index.html
{% extends "theme/_base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}
  {% translate "Licenses" %}
{% endblock title %}


{% block body %}

<h1>
  {% translate "Licenses" %}
</h1>

<div id="licenses-content-wrapper">

  <div class="d-flex">
    {% include "licenses/filters.html" %}

    <div id="add-license">
      {% include "licenses/includes/add_button.html" with style="btn btn-primary" %}
    </div>

  </div>

  <div
    id="licenses-list"
    hx-trigger="load"
    hx-get="{% url 'licenses:index' %}?{{ request.GET.urlencode|safe }}"
  >
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    {% comment %}
      {% include "licenses/licenses_table.html" %}
    {% endcomment %}
  </div>

</div>

{% endblock body %}

dlcdb/licenses/templates/licenses/licenses_table.html
{% load i18n %}

<style>
  .license-state img {
    max-width: 18px;
  }
</style>


<p class="text-muted small">
  <i>
    {{ licenses_filtered }} {% translate "of" %} {{ licenses_total }} {% translate "licences" %}.
    {% if licenses_filtered != licenses_total %}
      <a class="ms-1 badge text-bg-warning" href=".">
        <i class="bi bi-x-circle-fill"></i>
        {% translate "Show all?" %}
      </a>
    {% endif %}
  </i>
</p>

<table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>
          <!-- License status -->
        </th>
        <th>
          {% translate "License" %}
        </th>
        <th>
          {% translate "Start date" %}
        </th>
        <th>
          {% translate "Expiry date" %}
        </th>
        <th>
          {% translate "Subscribers" %}
          <a href="/docs/guides/lizenzen.html#subscribers">
            <i class="bi bi-info-circle-fill"></i>
          </a>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>

    {% for license in license_record_filter.qs %}
    <tr class="
    {% if license.license_state == 'expired' %}
    {% elif license.license_state == 'expiring' %}
      table-warning
    {% endif %}
    ">
        <td style="vertical-align: top;">
          {% include "licenses/traffic_light.html" %}
        </td>
      <td>
        {{ license.get_human_title }} ({{ license.device.sap_id }})


        <a
            href="{% url 'licenses:history' license.device.id %}"
            title="{% translate 'Show history' %}"
            class="mx-2"
        >
            <i class="bi bi-clock-history"></i>
        </a>

        {% if license.device.note or license.device.procurement_note %}
          <span class="text-primary">
            <i class="px-2 bi bi-chat-fill"></i>
          </span>
          <div id="note-{{ license.device.id }}" class="bg-white border rounded p-2 font-monospace mt-1 small d-none">
            {% if license.device.procurement_note %}
              <strong>{% translate "Procurement note" %}:</strong>
              {{ license.device.procurement_note|linebreaks }}
            {% endif %}

            {% if license.device.note and license.device.procurement_note %}
            <hr>
            {% endif %}

            {% if license.device.note %}
              <strong>{% translate "Note" %}:</strong>
              {{ license.device.note|linebreaks }}
            {% endif %}
          </div>
        {% endif %}
        <div>
          <span class="badge text-bg-secondary" title="{% translate 'License type' %}">
            {{ license.device.device_type|default:"n/a" }}
          </span>
        </div>
      </td>
      <td>
        {{ license.device.contract_start_date | default:"n/a" }}
        <br>
        <small class="text-muted">
          Order: {{ license.order_number|default:"n/a" }}
        </small>
      </td>
      <td>
        {{ license.device.contract_expiration_date|date:"Y-m-d"|default:"n/a" }}
      </td>
      <td class="small">
        {{ license.get_subscribers|default:""|linebreaksbr }}
      </td>
      <td>
        <a
            href="{% url 'licenses:edit' license_id=license.device.id %}"
            class="btn btn-primary btn-sm"

            {% comment %}
            hx-get="{% url 'licenses:edit' license_id=license.device.id %}"
            hx-trigger="click"
            hx-target="#licenses-content-wrapper"
            hx-push-url="true"
            {% endcomment %}
        >
            <i class="bi bi-pencil-square"></i>
        </a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="6" class="text-center">
        <i>
          {% translate "No licenses found." %}
          {% if licenses_total == 0 %}
            {% include "licenses/includes/add_button.html" with style="btn" %}
          {% endif %}
        </i>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


<script>
document.querySelectorAll('.bi.bi-chat-fill').forEach(function(stickyIcon) {
  if (!stickyIcon.hasListener) {
    stickyIcon.addEventListener('click', function() {
      let noteElement = this.parentElement.nextElementSibling;
      if (noteElement) {
        noteElement.classList.toggle('d-none');
      }
    });
    stickyIcon.hasListener = true;
  }
});
</script>

dlcdb/licenses/templates/licenses/playground.html
{% extends "theme/_base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}
  {% translate "Playground" %}
{% endblock title %}

{% block body %}

<h1>
  {% translate "Playground" %}
</h1>


{% endblock body %}

dlcdb/licenses/templates/licenses/timeline.html
<style>
    .timeline-row {
        position: relative;
        width: 100%;
        height: auto;
        display: flex;
    }
    .timeline-column {
        min-width: fit-content;
        padding: 0 2em 0 1em
    }
    .timeline-label {
        border-left: 2px solid white;
        padding-left: 4px;
    }
    .timeline .timeline-point:first-child .timeline-label {
        border-left-width: 0;
    }
</style>

<div class="timeline-row rounded text-bg-secondary my-4">
{% for event in events %}
    <div class="timeline-column timeline-point" style="width: {{ event.percentage }}%;">
        <div 
            class="
                timeline-label small 
                {% if event.event_type == 'today' %} fw-bold bg-success {% endif %}
            "
            style="{% if event.event_type == 'today' %} height: 70px; {% endif %}"
        >
            {{ event.date }}
            <br>
            {{ event.description }}
        </div>
    </div>
{% endfor %}
</div>

dlcdb/licenses/templates/licenses/traffic_light.html
<div class="license-state license-state-{{ license.license_state }}">
    <img
      src='data:image/svg+xml;charset=utf-8,{% include 'licenses/traffic_light.svg' with state=license.license_state %}'
      alt="{{ license.license_state }}"
      title="{{ license.get_license_state_label }}"
    >
  </div>