dlcdb/inventory/urls.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.InventorizeRoomListView.as_view(), name="inventorize-room-list"),
    path("room/<int:pk>/qrs/", views.QrCodesForRoomDetailView.as_view(), name="qr-room-printout"),
    path("room/<int:pk>/", views.InventorizeRoomView.as_view(), name="inventorize-room"),
    path("note-btn/<str:obj_type>/<uuid:obj_uuid>/", views.get_note_btn, name="get_note_btn"),
    path("note/<str:obj_type>/<uuid:obj_uuid>/", views.update_note_view, name="note-update"),
    path("misc/inventory_lending_report/", views.InventoryReportView.as_view(), name="inventory-lending-report"),
    path("devices/", views.search_devices, name="search-devices"),
    path("saplist/compare_sap_list/<int:pk>/", views.SapCompareListView.as_view(), name="compare-sap-list"),
    path("update-qrtoggle/", views.update_session_qrtoggle, name="update-qrtoggle"),
]

dlcdb/urls.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy
from django.contrib import admin
from django.views.generic.base import RedirectView

from dlcdb.organization import views as organization_views

admin.site.site_header = "DLCDB Admin"
admin.site.site_title = "DLCDB Admin"
admin.site.index_title = "DLCDB Administration"
admin.site.enable_nav_sidebar = False
admin.site.logout_template = "accounts/logout.html"


urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("core:core_dashboard"))),
    path("core/", include("dlcdb.core.urls")),
    path("inventory/", include("dlcdb.inventory.urls")),
    path("licenses/", include("dlcdb.licenses.urls")),
    path("smallstuff/", include("dlcdb.smallstuff.urls")),
    path("select2/", include("django_select2.urls")),
    path("api/v2/", include("dlcdb.api.urls")),
    path("favicon.ico", organization_views.favicon),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

dlcdb/core/models/note.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django.db import models


class Note(models.Model):
    """
    Represents a note. Notes are always bount to a device and optionally bount to an inventory.
    In case a note is bount to an inventory it was created during the inventory process.
    The inventory FK is also the basis to dump the comments.
    """

    text = models.TextField()
    device = models.ForeignKey(
        "core.Device",
        blank=True,
        null=True,
        related_name="device_notes",
        on_delete=models.SET_NULL,
    )
    room = models.ForeignKey(
        "core.Room",
        blank=True,
        null=True,
        related_name="room_notes",
        on_delete=models.SET_NULL,
    )
    inventory = models.ForeignKey(
        "core.Inventory",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="inventory_notes",
        verbose_name="Inventurzuordnung",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.EmailField(blank=True, editable=False)
    updated_by = models.EmailField(blank=True, editable=False)

    class Meta:
        # TODO: Define unique and unique_together constraints. Eg a
        # device could only have one inventory note per inventory.
        verbose_name = "Notiz"
        verbose_name_plural = "Notizen"
        indexes = [
            models.Index(fields=["created_at", "inventory"]),
        ]

    def __str__(self):
        return "{inventory} - {ts}".format(inventory=self.inventory or "", ts=self.created_at)

dlcdb/inventory/forms.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Field

from dlcdb.core.models import Note


class InventorizeRoomForm(forms.Form):
    uuids = forms.CharField(
        required=False,
        label="UUIDs state",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-sm",
                "readonly": "readonly",  # This makes the field read-only but still included in POST
            }
        ),
    )


class DeviceAddForm(forms.Form):
    def __init__(self, *args, **kwargs):
        add_devices_qs = kwargs.pop("add_devices_qs")
        device_choices = [("", "Add device")]
        device_choices += [(f"{str(d.uuid)}", f"{d.edv_id} {d.sap_id}") for d in add_devices_qs]
        super().__init__(*args, **kwargs)

        self.fields["device"] = forms.ChoiceField(
            choices=device_choices,
            # The BS5 .form-control class is applied via TomSelect
            # widget=forms.Select(attrs={"class": "form-control"}),
        )

    room = forms.CharField(widget=forms.HiddenInput())


class DeviceSearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_tag = False
        self.helper.disable_csrf = True

        self.helper.layout = Layout(
            Row(
                Column(Field("q", autofocus="on"), css_class="col-12 col-md-3"),
                Column("device_type", css_class="col-12 col-md-3"),
                Column("record", css_class="col-6 col-md-3"),
                Column("not_already_inventorized", css_class="col-6 col-md-3"),
            )
        )


# class RoomSearchForm(forms.Form):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.form_show_labels = False
#         self.helper.template_pack = "bootstrap4"
#         self.form_tag = False
#         self.helper.form_method = "get"
#         self.helper.disable_csrf = True
#         self.helper.layout = Layout(
#             FieldWithButtons(
#                 Field('q', autofocus="on"),
#                 StrictButton(
#                     '<i class="fas fa-search"></i>', type="submit", css_class="btn-sm btn btn-outline-primary"
#                 ),
#             ),
#         )


class NoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.hx_post_url = kwargs.pop("hx_post_url", None)
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_tag = False
        # self.helper.form_tag = True
        # self.helper.form_class = "form-inline note-update-form"
        # self.helper.attrs = {
        #     'hx_post': self.hx_post_url,
        #     'hx_target': 'this',
        #     'hx_on': "htmx:afterRequest: alert('Making a request!')",
        # }

    class Meta:
        model = Note
        fields = [
            "text",
            # Do not expose these fields, they are set via the view:
            # "room",
            # "inventory",
        ]

dlcdb/inventory/views.py
# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

"""
Inventory mode.

Goal: Verifiy all devices are "findable".

Subgoals:
* Room inventory should always be "saveable", even when not all devices are verified
* ...

Procedure:
* Go in room
* Check if expected device is in room
* Cases:
  * [FOUND]     Expected device is in room: confirm device
  * [NOT FOUND] Expected device is not in room: disprove device
  * [FOUND]     Not expected device is in room: add device to room and confirm device
* Room is finished, when all devices got their inventory stamp

TODO:
* Move domain-specific methods to the Inventory class (eg InventorizeRoomView.post stuff)
* Move queryset getters to Inventory class
* Refactor some CBVs to be FBVs
"""

import json
from datetime import date

from django.conf import settings
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseServerError, HttpResponseRedirect, JsonResponse
from django.template.response import TemplateResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist

from rest_framework.authtoken.models import Token
from django_filters.views import FilterView

from dlcdb.core.models import Room, Device, Inventory
from dlcdb.core.utils.helpers import get_user_email

from .sap import create_sap_list_comparison
from .filters import RoomFilter, DeviceFilter
from .forms import InventorizeRoomForm, DeviceAddForm, NoteForm
from .models import SapList


def update_session_qrtoggle(request):
    if request.method == "POST":
        data = json.loads(request.body)
        request.session["qrscanner_enabled"] = data["qrScanner"]
        # print(f"{request.session['qrscanner_enabled']=}")
        return JsonResponse(data)
    else:
        return HttpResponse("")


def get_js_vars(request):
    """
    Expose some Django settings and other variables to the frontend.
    Will be consumed via:

    ```html
    {{ js_vars|json_script:"js_vars" }}
    ```

    ```javascript
    const jsVars = JSON.parse(document.getElementById('js_vars').textContent);
    const qrToggleUrl = jsVars.qrToggleUrl;
    ```
    """

    js_vars = {
        "qrCodePrefix": settings.QRCODE_PREFIX,
        "djangoDebug": settings.DEBUG,
        "apiBaseUrl": f"{request.scheme}://{request.get_host()}/api/v2",
        "apiToken": Token.objects.first().key,
        "qrToggleUrl": reverse("inventory:update-qrtoggle"),
        "qrScannerEnabled": bool(request.session.get("qrscanner_enabled")),
    }

    return js_vars


class InventorizeRoomFormView(LoginRequiredMixin, SingleObjectMixin, FormView):
    template_name = "inventory/inventorize_room_detail.html"
    form_class = InventorizeRoomForm
    model = Room

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("inventory:inventorize-room", kwargs={"pk": self.object.pk})


@login_required
def inventorize_room(request, pk):
    template = "inventory/inventorize_room_detail.html"
    current_inventory = Inventory.objects.active_inventory()
    tenant = request.tenant
    is_superuser = request.user.is_superuser

    if not current_inventory:
        context = {
            "current_inventory": current_inventory,
        }

    else:
        devices_in_room = Inventory.objects.tenant_aware_device_objects_for_room(
            pk, tenant=tenant, is_superuser=is_superuser
        )

        # Allow only adding devices which are not already present in this room:
        add_devices_qs = Inventory.objects.tenant_aware_device_objects(
            tenant=tenant, is_superuser=is_superuser
        ).exclude(active_record__room=pk)

        device_add_form = DeviceAddForm(
            add_devices_qs=add_devices_qs,
            initial={
                "room": pk,
            },
        )

        inventory_progress = current_inventory.get_inventory_progress(
            tenant=tenant,
            is_superuser=is_superuser,
        )

        context = {
            "room": Inventory.objects.tenant_aware_room_objects(tenant=tenant).get(pk=pk),
            "devices": devices_in_room,
            "current_inventory": current_inventory,
            "dev_state_unknown": "dev_state_unknown",
            "dev_state_found": "dev_state_found",
            # 'dev_state_found_unexpected': 'dev_state_found_unexpected',
            "dev_state_notfound": "dev_state_notfound",
            "dev_state_added": "dev_state_added",
            "form": InventorizeRoomForm(),
            "device_add_form": device_add_form,
            "inventory_progress": inventory_progress,
            "debug": settings.DEBUG,
            "js_vars": get_js_vars(request),
        }

    return TemplateResponse(request, template, context)


class InventorizeRoomView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return inventorize_room(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = InventorizeRoomFormView.as_view()

        uuids = request.POST.get("uuids")
        room_pk = self.kwargs.get("pk")

        try:
            if uuids:
                Inventory.inventorize_uuids_for_room(uuids=uuids, room_pk=room_pk, user=request.user)
            else:
                messages.add_message(request, messages.WARNING, "Nothing marked as inventorized.")
        except RuntimeError as runtime_error:
            return HttpResponseServerError(runtime_error)
        except ObjectDoesNotExist as object_does_not_exist:
            return HttpResponseServerError(object_does_not_exist)

        return view(request, *args, **kwargs)


class InventorizeRoomListView(LoginRequiredMixin, FilterView):
    model = Room
    context_object_name = "rooms"
    filterset_class = RoomFilter

    def get_queryset(self):
        try:
            qs = Inventory.objects.tenant_aware_room_objects(self.request.tenant)
        except Inventory.DoesNotExist:
            qs = Room.objects.all()

        return qs

    def get_template_names(self):
        if self.request.htmx:
            return ["inventory/partials/room_list.html"]
        else:
            return ["inventory/inventorize_room_list.html"]

    def get_context_data(self, **kwargs):
        # Capture URL query parameters to persist pagination
        _request_copy = self.request.GET.copy()
        parameters = _request_copy.pop("page", True) and _request_copy.urlencode()

        current_inventory = Inventory.objects.active_inventory()

        if current_inventory:
            inventory_progress = current_inventory.get_inventory_progress(
                tenant=self.request.tenant,
                is_superuser=self.request.user.is_superuser,
            )
        else:
            inventory_progress = None

        context = super().get_context_data(**kwargs)
        context.update(
            {
                "current_inventory": current_inventory,
                "parameters": parameters,
                "inventory_progress": inventory_progress,
                "js_vars": get_js_vars(self.request),
            }
        )
        return context

    def render_to_response(self, context, **response_kwargs):
        response = super().render_to_response(context, **response_kwargs)

        # if self.request.htmx and self.request.META.get("QUERY_STRING"):
        #     response["HX-Push-Url"] = f"{self.request.path}?{self.request.META.get('QUERY_STRING')}"

        return response


@login_required
def search_devices(request):
    if request.htmx:
        template = "inventory/partials/device_search_htmx.html"
    else:
        template = "inventory/device_search.html"

    all_devices = Inventory.objects.inventory_relevant_devices(
        tenant=request.tenant, is_superuser=request.user.is_superuser
    )
    filter_devices = DeviceFilter(request.GET, queryset=all_devices)

    request_copy = request.GET.copy()
    parameters = request_copy.pop("page", True) and request_copy.urlencode()

    paginator = Paginator(filter_devices.qs, 25)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "current_inventory": Inventory.objects.active_inventory(),
        "page_obj": page_obj,
        "filter_devices": filter_devices,
        "all_devices_count": all_devices.count(),
        "parameters": parameters,
    }
    return TemplateResponse(request, template, context)


class QrCodesForRoomDetailView(LoginRequiredMixin, DetailView):
    model = Room
    context_object_name = "room"
    template_name = "inventory/room_qrcodes_detail.html"

    def get_context_data(self, **kwargs):
        devices = Inventory.objects.tenant_aware_device_objects_for_room(
            self.object.pk, tenant=self.request.tenant, is_superuser=self.request.user.is_superuser
        )
        context = super().get_context_data(**kwargs)
        context["devices"] = devices
        return context


class InventoryReportView(TemplateView):
    template_name = "inventory/inventorize_report.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "devices": Inventory.objects.lent_devices().order_by("sap_id"),
                "now": date.today(),
            }
        )
        return context

dlcdb/inventory/templates/inventory/includes/inventory_progress.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

{% comment %}
    {% load cache %}
    {% cache 60 inventory_progress request.user.username %}
    {% endcache %}
{% endcomment %}


<div class="progress bg-primary" style="height: 2rem;">
    <div 
        class="font-weight-bold progress-bar progress-bar-striped bg-success" 
        role="progressbar" 
        style="overflow: visible; min-width: 5%; width: {{ inventory_progress.done_percent }}%;" 
        aria-valuenow="{{ inventory_progress.done_percent }}" 
        aria-valuemin="0" 
        aria-valuemax="100"
        title="Inventory progress for current tenant, counting only devices with an inventory id"
    >
        {{ inventory_progress.done_percent }}% 
        ({{ inventory_progress.inventorized_devices_count }} / {{ inventory_progress.all_devices_count }} Devices)
    </div>
</div>

dlcdb/inventory/templates/inventory/includes/inventory_status_badge.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

{% if style == "badge" %}
    <span class="badge text-bg-{{ room.get_inventory_status.css_class }}">
        {{ room.get_inventory_status.n_of_ns }}
    </span>
{% else %}
    <span class="btn btn-sm btn-{{ room.get_inventory_status.css_class }}">
        <span class="badge text-bg-light">
            {{ room.get_inventory_status.n_of_ns }}
        </span>
        {{ room.get_inventory_status.status_str }}
    </span>
{% endif %}

dlcdb/inventory/templates/inventory/includes/note_btn.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

{# <pre>{{ obj_type }} / {{ obj }} / {{ obj.uuid }}</pre> #}
<button 
    {% if obj_type == "device" %}
        hx-get="{% url 'inventory:note-update' obj_type=obj_type obj_uuid=obj_uuid %}"
    {% else %}
        hx-get="{% url 'inventory:note-update' obj_type=obj_type obj_uuid=obj.uuid %}"
    {% endif %}
    hx-target="#dialog"
    class="note-btn btn btn-sm btn-outline-primary"
>
    {% if obj.has_inventory_note %}
        <i class="fas fa-comment-alt"></i>
    {% else %}
        <i class="far fa-comment-alt"></i>
    {% endif %}
</button>

dlcdb/inventory/templates/inventory/includes/note_form.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

{% load crispy_forms_tags %}


<div class="modal-content">
    <form 
        hx-post="{{ hx_post_url }}"
    >
        <div class="modal-header">
            <h5 class="modal-title">Edit Note for {{ note_object }}</h5>
        </div>
        <div class="modal-body">
            {% crispy form %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

dlcdb/inventory/templates/inventory/includes/pagination.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

<nav>
    <ul class="pagination justify-content-end">
        
    {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ parameters }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
    {% else %}
        <li class="page-item disabled">
        <span class="page-link">
            <span aria-hidden="true">&laquo;</span>
        </span>
        </li>
    {% endif %}

    <li class="page-item active disabled" aria-current="page">
        <span class="page-link text-center">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
    </li>

    {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ parameters }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
    {% else %}
        <li class="page-item disabled">
        <span class="page-link">
            <span aria-hidden="true">&raquo;</span>
        </span>
        </li>
    {% endif %}
    </ul>
</nav>

dlcdb/inventory/templates/inventory/includes/pagination_htmx.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

<nav>
    <ul class="pagination justify-content-end">

    {% if page_obj.has_previous %}
        <li class="page-item">
            <span
                title="First page"
                role="button"
                class="page-link"
                hx-get="?page=1&{{ parameters }}"
            >
                <i class="fa-solid fa-angles-left"></i>
            </span>
        </li>
        <li class="page-item">
            <span 
                title="Previous page"
                role="button"
                class="page-link" 
                hx-get="?page={{ page_obj.previous_page_number }}&{{ parameters }}"
            >
                <i class="fa-solid fa-angle-left"></i>
            </span>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span
                title="Next page"
                class="page-link"
            >
                <i class="fa-solid fa-angles-left"></i>
            </span>
        </li>
        <li class="page-item disabled">
            <span 
                title="First page"
                class="page-link"
            >
                <i class="fa-solid fa-angle-left"></i>
            </span>
        </li>
    {% endif %}

    <li class="page-item active disabled" aria-current="page">
        <span class="page-link text-center">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
    </li>

    {% if page_obj.has_next %}
        <li class="page-item">
            <span 
                title="Next page"
                role="button"
                class="page-link"
                hx-get="?page={{ page_obj.next_page_number }}&{{ parameters }}"
            >
                <i class="fa-solid fa-angle-right"></i>
            </span>
        </li>
        <li class="page-item">
            <span
                title="Last page"
                role="button"
                class="page-link"
                hx-get="?page={{ page_obj.paginator.num_pages }}&{{ parameters }}"
            >
                <i class="fa-solid fa-angles-right"></i>
            </span>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span 
                title="Next page"
                class="page-link"
            >
                <i class="fa-solid fa-angle-right"></i>
            </span>
        </li>
        <li class="page-item disabled">
            <span
                title="Last page"
                role="button"
                class="page-link"
            >
                <i class="fa-solid fa-angles-right"></i>
            </span>
        </li>
    {% endif %}
    </ul>
</nav>

dlcdb/inventory/templates/inventory/includes/qrvideo.html
<!--
SPDX-FileCopyrightText: 2024 Thomas Breitner

SPDX-License-Identifier: EUPL-1.2
-->

{% if request.session.qrscanner_enabled == 1 %}

<div class="rounded bg-light my-2">
<div class="row">
    <div class="col">
        {% if room %}
        <a href="{% url 'inventory:qr-room-printout' room.pk %}">
            <img 
                src="{{ room.qrcode.url }}" 
                style="width: 60px; height: 60px"
            >
        </a>
        {% endif %}
        <span id="cam-has-camera" style="display: none;"></span>
    </div>
    <div class="col">
        <video muted playsinline 
            id="qr-video" 
            style="max-height: 200px; max-width: 200px;">
        </video>
    </div>
    <div class="col">
        <b>Detected QR code: </b>
        <span id="cam-qr-result">None</span>
        <br>
        <b>Last detected at: </b>
        <span id="cam-qr-result-timestamp"></span>
    </div>
</div>
</div>

{% endif %}

dlcdb/inventory/templates/inventory/includes/record_info.html
<small
    class="badge text-bg-warning"
    title="Current record created at {{ device.active_record.created_at|date:"Y-m-d" }}, {{ device.active_record.created_at|timesince }} ago"
>
    {% if device.already_inventorized %}
        <span >
            {{ current_inventory.name }}
        </span>
        <br>
    {% endif %}

    <span>
        {{ device.active_record.created_at|date:"Y-m-d" }}
    </span>
</small>